name = "fabricaborgbots"
main = "src/index.ts"
compatibility_date = "2026-06-14"

preview_urls = false

[vars]
AI_MODEL_NAME = "gemini-2.5-flash"

[[d1_databases]]
binding = "DB"
database_name = "bot_factory_db"
database_id = "707affde-e219-4b26-b5bd-d110c318364d"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
